name = "MyLittleModpack"
author = "Sollace, Fauli1221"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
no-internal-hashes = true
