hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/big-pony.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons-extras.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/missing-wilds.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/seasonhud-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/stringer-things.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia.pw.toml"
metafile = true

[[files]]
file = "mods/void-fog.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true
